### ISSUE TITLE
Unique Migration Waves

### ISSUE THREAD

**Issue by gildub** [konveyor/tackle2-ui#1039]
The initial design has migration waves' name optional.
When waves don't have name, the user can distinct them from their start and end dates meanwhile to help avoid creating identical wave we cannot do that if the name is optional.

One solution is to have a composite unique key for each migration wave record using `name`, `startDate` and `endDate` fields, where `name` field is not NULL.

**Comment by rromannissen** [comment]
I don't think there is a need for this. I guess it's just a matter of having a logic that implements the following:

- If the name is null, there can't be two waves with the same startDate and endDate. 
- If the name is not null, there can't be two waves with the same name, startDate and endDate. 

So instead of a key, this would be handled by validation logic.

**Comment by gildub** [comment]
@rromannissen,  that makes sense.

My concern is to have the same business rules validation on both UI and API to not leave cracks open.

@jortel, @mansam, what do you think ?

**Comment by gildub** [comment]
@jortel, could the name be null as well ?
