### ISSUE TITLE
Jira configuration: Not connected message needs adjustment 

### ISSUE THREAD

**Issue by gildub** [konveyor/tackle2-ui#1067]
The error message of a failed connection can be quite long and needs to be display correctly:

![image](https://github.com/konveyor/tackle2-ui/assets/1901741/b2221097-4d24-480b-bcd1-2056e1eaa956)

**Comment by sjd78** [comment]
To get this crazy looking error:
 1. Create a Jira credential with something that will not work (bearer or basic doesn't matter)
 2. Create a new jira configuration to a real jira instance
 3. Use the bad credential created in 1
 4. Wait a bit and the "Not connected" popover will populate with a crazy long error message

When I took a look at the error message, it turns out to be the full HTTP response with error code 403...

A snip of what I saw:
```
403 Forbidden: 










<html>

<head>
    <title>Forbidden (403)</title>
    





[removed the script blocks]

    <meta name=\"application-name\" content=\"JIRA\" data-name=\"jira\" data-version=\"9.4.2\">
</head>
<body id=\"jira\" class=\"aui-layout aui-style-default page-type-message \" data-version=\"9.4.2\" >

<!-- HTTPError403 -->
    <div class=\"aui-page-panel\" ><div class=\"aui-page-panel-inner\">
            <main role=\"main\" id=\"main\" class=\"aui-page-panel-content\" >
                    <div class=\"aui-page-header\" ><div class=\"aui-page-header-inner\">
                            <div class=\"aui-page-header-main\" >
                                    <h1>Forbidden (403)</h1>
                                </div>
                        </div></div>
                    <div class=\"aui-message aui-message-warning warning\">
                            <p>Encountered a <code>&quot;403 - Forbidden&quot;</code> error while loading this page.</p>
                            <p>Basic Authentication Failure - Reason : AUTHENTICATION_DENIED</p>
                            <p><a href=\"/secure/MyJiraHome.jspa\">Go to Jira home</a></p>
                        </div>
                </main>
        </div></div>
</body>
</html>
: request failed. Please analyze the request body for more details. Status code: 403
```

I can adjust the display to handle content like this.

However, why is content like this even passed back to us in the REST api as a message?  Does it make sense to open a related issue on hub?

cc: @gildub , @ibolton336
