### ISSUE TITLE
Duplicate StatusIcon references 

### ISSUE THREAD

**Issue by ibolton336** [konveyor/tackle2-ui#1070]
We are using a few components with the same name "statusIcon" that operate differently & exist in two different locations (one locally & one in the external lib-ui package)

**Comment by ibolton336** [comment]
Looks like the only two uses of the lib-ui statusIcon are in tracker-status & manage-imports. I wonder if we could just use our own here to be consistent. Otherwise yeah a rename would probably be fine. The lib-ui implementation is just missing a few icons/labels that we are using in our project.

**Comment by gitdallas** [comment]
@ibolton336 - i looked a bit and our lib-ui uses have some more complex cases such as adding poppers within the label. It looks like lib-ui is also owned by you (migtools.. mig = mike+ian+gilles?). Might actually make more sense to update the lib-ui to either have more status types or allow custom. WDYT?

Otherwise the quick way would be just to rename if we don't want to use a name that matches something we are importing.

**Comment by ibolton336** [comment]
@gitdallas I actually had the same idea https://github.com/migtools/lib-ui/pull/129/files but after discussing with @mturley , decided against extending the use case of the lib-ui component for a few reasons. Mainly - there just isn't enough meat on that custom component to warrant extending it. We could just render our label and text without consuming anything custom from lib-ui. It does provide the perk of a more structured layout with flex box, but that is where the value added sort of ends. I am leaning toward just reworking our icons in a way that doesn't require this external component since we have already gone down the route of building something exclusive in our tackle2-ui codebase.

**Comment by mturley** [comment]
@ibolton336 I'm totally in support of getting rid of the external StatusIcon component and removing it from lib-ui entirely. It has outlived its original use case: lining up icons with text properly and assigning the right color to them to match status.

I went back to look at the icon component in PF and they've since made both of those things easier:
```tsx
      <Text component="p">
        <Icon isInline status="danger">
          <ExclamationCircleIcon />
        </Icon>
        Danger
      </Text>
```

![Screenshot 2023-07-27 at 4 17 11 PM](https://github.com/konveyor/tackle2-ui/assets/811963/e255ce4d-333c-4e6e-bc97-bd5e78e1fbae)

**Comment by mturley** [comment]
It probably makes sense to get rid of lib-ui's StatusIcon, refactor tackle2-ui's StatusIcon to use the `isInline` and `status` props instead of its custom flexbox and color variables, and then evaluate whether there is still any value in having that component.

**Comment by gitdallas** [comment]
create a pr just getting the internal statusicon to work for where the lib-ui one was being used.

can look into updating the markup of statusicon or removing it... for this issue or another?

**Comment by mturley** [comment]
Probably a separate issue

**Comment by gitdallas** [comment]
@mturley  - i already went ahead and updated the markup in the status-icon, but we could still do a separate issue if we want to remove the component all together.

**Comment by mturley** [comment]
oh that's totally fine. thanks
