### ISSUE TITLE
Application Form tags representation UX improvement

### ISSUE THREAD

**Issue by ibolton336** [konveyor/tackle2-ui#1410]
- Currently, the application form allows selection of tags from all available tags from the tags api. This could potentially result in a duplicate tag existing on an application if the user manually adds a tag that was already applied to an application via another source (analysis, assessment, or archetype membership). 

There is some room to improve this UX by potentially: 
  - Displaying existing tag relationships in the application edit form 
  - Hiding already associated tags from the selections options for application tags

**Comment by ibolton336** [comment]
https://github.com/konveyor/tackle2-ui/pull/1403#issuecomment-1738075566

**Comment by sjd78** [comment]
PR #1408 enables making these kinds of changes.  Disallowing the selection of tags that have already been selected by another source (analysis, application assessment, archetype, archetype assessment) should be a matter of filtering the source options list.

UX design for showing the non-manual Tags (i.e. `TagRef` with a non-empty `source`) would be helpful.

**Comment by sjd78** [comment]
After following up with Ramon and Justin --

  - The application form will show only manual tags (i.e. source = "")

  - The manual tag list will present all tags since having the same tag from multiple sources can be good information in an of itself

  - The label on the tag list will be changed to "Manual Tag(s)" to match the view in the application drawer
