### ISSUE TITLE
[BUG] Dependencies Found in "application" is missing blue color highlighter

### ISSUE THREAD

**Issue by kpunwatk** [konveyor/tackle2-ui#1697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

main

### Priority

Minor

### Current Behavior

![Screenshot from 2024-02-22 22-09-40](https://github.com/konveyor/tackle2-ui/assets/87791967/4b0a08a5-ebc1-416f-9877-c26fca7dab18)
In Dendencies>> Found In "Application" is missing blue color as it it's a hyperlink navigate to application Inventory page 

### How Reproducible

Always (Default)

### Environment

```markdown
- OS:
```

**Comment by ibolton336** [comment]
Was this discussed as a feature request & was just never implemented? @kpunwatk

**Comment by JustinXHale** [comment]
I believe that if we isolate this page and view it independently, there might be a brief moment of confusion regarding its lack of apparent actions. However, once users navigate to this page after exploring our entire system, its alignment with the established patterns in Konveyor becomes clearer. For instance, on the **Application Inventory** page, there are not blue links associated with the application name  to signify the opening of a side drawer. This consistency extends to **Archetypes** as well. Generally, throughout our system, we consistently utilize blue links to direct users to different pages rather than to open drawers. The only exception to this convention is found on the Migration Waves page.

I am in favor of maintaining the current layout of the page. It aligns well with the overall user experience in Konveyor, reflecting the approach taken on the Application Inventory page.

![image](https://github.com/konveyor/tackle2-ui/assets/91554933/d63868e1-ad54-43a1-9bed-bf3acedc219d)
![image](https://github.com/konveyor/tackle2-ui/assets/91554933/3973e9ed-c0f2-4a25-8944-deccd4376cfc)
