### ISSUE TITLE
[BUG] Harmonize the render of task data between the task drawer and the task table

### ISSUE THREAD

**Issue by sjd78** [konveyor/tackle2-ui#1969]
Followup to: #1955, #1957 

The task manager drawer and the task table both have code to render tasks.  We should look at the code and extract common work to maintain visual content consistency across the UI.

This can include:
  - Status icons
  - Status icon tooltips
  - create, start, terminate date formats and intervals

**Comment by rszwajko** [comment]
@sjd78 
Created #1994  as part of this issue. The improvement here is to be better at displaying local time. The format will be still different then in the drawer because use cases are different - in the table we need an easy way to establish a sort order which makes ISO 8601 is a better choice. In the drawer we can keep the humanized/localized formats.

**Comment by rszwajko** [comment]
Moved the remaining part to a separate issue to be handled in the next release cycle.
