### ISSUE TITLE
View report / task data in yaml

### ISSUE THREAD

**Issue by ibolton336** [konveyor/tackle2-ui#835]
- Display api fetched data for task details in yaml format

**Comment by gildub** [comment]
@ibolton336, is this still on the radar as the analyzers report format was going to cover for it ?

**Comment by sjd78** [comment]
Duplicated by https://issues.redhat.com/browse/MTA-773

With the current way of opening the details, only the default mime type for the service endpoint can be used:

```jsx
        onClick: () => {
          const task = getTask(row);
          if (task) window.open(`/hub/tasks/${task.id}`, "_blank");
        },
```

```jsx
  const openAnalysisDetails = () => {
    if (task) window.open(`/hub/tasks/${task.id}`, "_blank");
  };
```

A reasonable way forward would be to use a `CodeEditor` component in read-only mode similar to the `FactCodeSnipViewer` of #1057.

Maybe navigate to a new route in the normal application page?

Maybe have a skinny viewer app using a separate webpack entry point all together?

Thoughts @ibolton336 , @gildub , @mturley ?

**Comment by mturley** [comment]
I think we probably don't want to take the user away from their current browser tab for this if we can help it (I know we currently do, but I think that was out of convenience since this was the easiest way to pull up raw data?)

My vote would be to open a modal with a read-only code viewer, just like #1057 as suggested.
